modLoader="kotlinfml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/autaut03/roomery/issues"
displayURL="https://github.com/autaut03/roomery"
logoFile="examplemod.png"
credits="MCP, FML, Forge guys; CompactMachines3 mod"
authors="Alex_Wells (autaut03)"

[[mods]]
    modId="roomery"
    version="${file.jarVersion}"
    displayName="Roomery"
    updateJSONURL="https://raw.githubusercontent.com/autaut03/roomery/master/update.json"
    description="Create whole rooms inside a single block"

[[dependencies.roomery]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.roomery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2,)"
    ordering="NONE"
    side="BOTH"